FREE_LOOKAHEAD = 1.6
MID_LOOKAHEAD = 1.1
DANGER_LOOKAHEAD = 0.8

VELO_MULT = 20

FREE_VELO_MULT = 1
MID_VELO_MULT = 0.8
DANGER_VELO_MULT = 0.6

MIN_SPEED = 20
MAX_SPEED = 80

LOOKAHEAD_DISTANCE = 1.2
STEERING_MULTIPLIER = 3.8
