MAX_LIDAR_DISTANCE = 3
STEERING_MULTIPLIER = 3.3
MINIMUM_SPEED = 10
MAXIMUM_SPEED = 25

DISPARITY_DISTANCE = 0.3
SAFETY_EXTENSION = 25

GAP_SELECTION = "best" # least_steering, widest, deepest, largest_integral
POINT_SELECTION = "best" # lear_steering, middle, deepest
MIN_GAP_SIZE = 10
MIN_GAP_DISTANCE = 2
CORNERING_DISTANCE = 0.28
