MAX_LIDAR_DISTANCE = 2.5
STEERING_MULTIPLIER = 3
MINIMUM_SPEED = 15
MAXIMUM_SPEED = 40

DISPARITY_DISTANCE = 0.3
SAFETY_EXTENSION = 35

GAP_SELECTION = "deepest" # least_steering, widest, deepest, largest_integral
POINT_SELECTION = "deepest" # lear_steering, middle, deepest
MIN_GAP_SIZE = 10
MIN_GAP_DISTANCE = 2
CORNERING_DISTANCE = 0.05
